version: "2"

networks:
  animal-shelter:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - animal-shelter
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - animal-shelter
  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    networks:
      - animal-shelter
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres:5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - KAFKA_HOST=kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - animal-shelter

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
