INSERT INTO ANIMAL (ID, NAME, BREED, GENDER, VACCINATED) SELECT 1, 'Bigotes', 'Birmano', 'Male', TRUE WHERE NOT EXISTS (SELECT 1 FROM ANIMAL WHERE ID = 1);
INSERT INTO VACCINE (ID, NAME) SELECT 1, 'Moquillo' WHERE  NOT EXISTS (SELECT 1 FROM VACCINE WHERE ID = 1);
INSERT INTO VACCINE (ID, NAME) SELECT 2, 'Gripe Felina' WHERE  NOT EXISTS (SELECT 1 FROM VACCINE WHERE ID = 2);
INSERT INTO VACCINE (ID, NAME) SELECT 3, 'Leucemia Felina' WHERE  NOT EXISTS (SELECT 1 FROM VACCINE WHERE ID = 3);
INSERT INTO VACCINE (ID, NAME) SELECT 4, 'Peritonitis Infecciosa Felina' WHERE  NOT EXISTS (SELECT 1 FROM VACCINE WHERE ID = 4);
INSERT INTO VACCINE (ID, NAME) SELECT 5, 'Rabia' WHERE  NOT EXISTS (SELECT 1 FROM VACCINE WHERE ID = 5);

INSERT INTO VACCINES_BY_ANIMAL (ANIMAL_ID, VACCINE_ID) SELECT 1, 5 WHERE NOT EXISTS (SELECT 1 FROM VACCINES_BY_ANIMAL WHERE ANIMAL_ID = 1 AND VACCINE_ID = 5);
